#pragma once

#define DISCOFLOOR_STRINGIFY_IMPL(x) #x
#define DISCOFLOOR_STRINGIFY(x) DISCOFLOOR_STRINGIFY_IMPL(x)

#define DISCOFLOOR_VERSION_MAJOR 1
#define DISCOFLOOR_VERSION_MINOR 0
#define DISCOFLOOR_VERSION_PATCH 0
#define DISCOFLOOR_VERSION_SUFFIX "-pre"

#define DISCOFLOOR_VERSION_STRING \
	DISCOFLOOR_STRINGIFY(DISCOFLOOR_VERSION_MAJOR) "." \
	DISCOFLOOR_STRINGIFY(DISCOFLOOR_VERSION_MINOR) "." \
	DISCOFLOOR_STRINGIFY(DISCOFLOOR_VERSION_PATCH) \
	DISCOFLOOR_VERSION_SUFFIX